# Generated by Django 4.2 on 2023-04-25 23:32

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research_project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="instrumenttype",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AddField(
            model_name="instrumenttype",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="research_project",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AddField(
            model_name="research_project",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now, editable=False, verbose_name="created"
            ),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now, editable=False, verbose_name="modified"
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="research_project",
            field=models.ForeignKey(
                blank=True,
                help_text="The research_project to which the instrument belongs.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="research_project.research_project",
                verbose_name="research_project",
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="type",
            field=models.ForeignKey(
                help_text="The research_project to which the instrument belongs.",
                on_delete=django.db.models.deletion.PROTECT,
                to="research_project.instrumenttype",
                verbose_name="instrument type",
            ),
        ),
    ]
